---
apiVersion: v1
kind: Pod
metadata:
  name: liveness

spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80  
      args:
        - /bin/sh
        - -c
        - touch /tmp/flm; sleep 1000
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/flm
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 30  


